local opts = require("tairiki.config").options
local p = require("tairiki").palette[vim.o.background] or opts.palette
local c = require("tairiki.palette").load(p)

return {
  normal = {
    bg = c.none,
    fg = c.fg_dark,
  },
  ellipsis = { fg = c.fg_dark3 },
  separator = { fg = c.fg_dark3 },
  modified = { fg = c.diag.warn },
  dirname = {},
  basename = { fg = c.fg, bold = true },
  context = {},
  context_file = { fg = c.blue },
  context_module = { fg = c.blue },
  context_namespace = { fg = c.purple },
  context_package = { fg = c.syn.special },
  context_class = { fg = c.yellow },
  context_method = { fg = c.blue },
  context_property = { fg = c.cyan },
  context_field = { fg = c.cyan },
  context_constructor = { fg = c.yellow },
  context_enum = { fg = c.orange },
  context_interface = { fg = c.yellow },
  context_function = { fg = c.blue },
  context_variable = { fg = c.purple },
  context_constant = { fg = c.orange },
  context_string = { fg = c.green },
  context_number = { fg = c.syn.literal },
  context_boolean = { fg = c.syn.literal },
  context_array = { fg = c.yellow },
  context_object = { fg = c.yellow },
  context_key = { fg = c.purple },
  context_null = { fg = c.red },
  context_enum_member = { fg = c.yellow },
  context_struct = { fg = c.purple },
  context_event = { fg = c.yellow },
  context_operator = { fg = c.red },
  context_type_parameter = { fg = c.red },
}
