local c = require("tairiki.colors")

return {
  normal = {
    bg = c.none,
    fg = c.light_grey,
  },
  ellipsis = { fg = c.grey },
  separator = { fg = c.grey },
  modified = { fg = c.green },
  dirname = {},
  basename = { fg = c.fg, bold = true },
  context = {},
  context_file = { fg = c.blue },
  context_module = { fg = c.orange },
  context_namespace = { fg = c.orange },
  context_package = { fg = c.orange },
  context_class = { fg = c.yellow },
  context_method = { fg = c.blue },
  context_property = { fg = c.cyan },
  context_field = { fg = c.cyan },
  context_constructor = { fg = c.yellow },
  context_enum = { fg = c.ornage },
  context_interface = { fg = c.yellow },
  context_function = { fg = c.blue },
  context_variable = { fg = c.purple },
  context_constant = { fg = c.orange },
  context_string = { fg = c.green },
  context_number = { fg = c.light_orange },
  context_boolean = { fg = c.light_orange },
  context_array = { fg = c.yellow },
  context_object = { fg = c.yellow },
  context_key = { fg = c.purple },
  context_null = { fg = c.red },
  context_enum_member = { fg = c.yellow },
  context_struct = { fg = c.purple },
  context_event = { fg = c.yellow },
  context_operator = { fg = c.red },
  context_type_parameter = { fg = c.red },
}
