[colors.primary]
background = '#151515'
foreground = '#c5c8c6'

[colors.cursor]
text = '#151515'
cursor = '#ffffff'

[colors.normal]
black   = '#151515'
red     = '#cc6666'
green   = '#b5bd68'
yellow  = '#e6c547'
blue    = '#81a2be'
magenta = '#b294bb'
cyan    = '#70c0ba'
white   = '#373b41'

[colors.bright]
black   = '#666666'
red     = '#ff3334'
green   = '#9ec400'
yellow  = '#f0c674'
blue    = '#81a2be'
magenta = '#b77ee0'
cyan    = '#54ced6'
white   = '#282a2e'
