[colors.primary]
background = '#151515'
foreground = '#c5c8c6'

[colors.normal]
black   = '#3b3f4c'
red     = '#cc6666'
green   = '#b5bd68'
yellow  = '#e6c547'
blue    = '#81a2be'
magenta = '#b294bb'
cyan    = '#70c0ba'
white   = '#c5c8c6'

[colors.bright]
black   = '#666666'
red     = '#cc6666'
green   = '#b5bd68'
yellow  = '#e6c547'
blue    = '#81a2be'
magenta = '#b294bb'
cyan    = '#70c0ba'
white   = '#f5f8f6'
